// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyg9I8ft_2Ap2EQRZu-LeX08lxWp2Obp8',
    appId: '1:251311764335:web:b9ee2b22eefa7fae7d2e9a',
    messagingSenderId: '251311764335',
    projectId: 'serenest-51ca9',
    authDomain: 'serenest-51ca9.firebaseapp.com',
    storageBucket: 'serenest-51ca9.firebasestorage.app',
    measurementId: 'G-M4FT9ESD2L',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCoF9G16Qmn7Y4o9Pmcdl5EQLEQ0kxcnWw',
    appId: '1:251311764335:ios:97d6bbdaff820d047d2e9a',
    messagingSenderId: '251311764335',
    projectId: 'serenest-51ca9',
    storageBucket: 'serenest-51ca9.firebasestorage.app',
    iosBundleId: 'com.example.doctorAppointment',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCyg9I8ft_2Ap2EQRZu-LeX08lxWp2Obp8',
    appId: '1:251311764335:web:cfabd068acdb03ea7d2e9a',
    messagingSenderId: '251311764335',
    projectId: 'serenest-51ca9',
    authDomain: 'serenest-51ca9.firebaseapp.com',
    storageBucket: 'serenest-51ca9.firebasestorage.app',
    measurementId: 'G-DNY351H333',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCoF9G16Qmn7Y4o9Pmcdl5EQLEQ0kxcnWw',
    appId: '1:251311764335:ios:97d6bbdaff820d047d2e9a',
    messagingSenderId: '251311764335',
    projectId: 'serenest-51ca9',
    storageBucket: 'serenest-51ca9.firebasestorage.app',
    iosBundleId: 'com.example.doctorAppointment',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADurtNGsGEqd3_IRfSiL2zmSqX8eLfOgM',
    appId: '1:251311764335:android:6b7c2be7ba83760b7d2e9a',
    messagingSenderId: '251311764335',
    projectId: 'serenest-51ca9',
    storageBucket: 'serenest-51ca9.firebasestorage.app',
  );

}